### ISSUE TITLE
Setup CI/CD for our custom plugins

### ISSUE THREAD

**Issue by orlando** [debtcollective/community#10]
We want to test plugins in the testing environment (https://github.com/debtcollective/community/issues/9) after we merge changes to master. 

The goal is to set up continuous deployment to the testing instance with Travis CI

## Acceptance Criteria

- Our plugins are deployed to the testing instance when we merge new code to master.

**Comment by duranmla** [comment]
As we ar going to migrate out of plugins do we still need this?
