### ISSUE TITLE
Add background color to global pinned topics

### ISSUE THREAD

**Issue by orlando** [debtcollective/community#12]
We what to make the pinned topics a bit more relevant and to attract users attention.

![image](https://user-images.githubusercontent.com/849872/60134319-df46e580-9764-11e9-84cd-e087dccbb8f2.png)

## Acceptance Criteria

- Add a background to global pinned topics

**Comment by duranmla** [comment]
As we are doing a full theme customisation and the relevance of pinned topics has been handle in a different way. Check https://www.figma.com/file/iab7UEbGQhAWcsubYZ9cWB/community-mockups?node-id=0%3A233
