### ISSUE TITLE
New user post notice is bigger than the messages container

### ISSUE THREAD

**Issue by orlando** [debtcollective/community#16]
**What:** New user post notice is bigger than the messages container

![image](https://user-images.githubusercontent.com/849872/63135074-f4d0d280-bf91-11e9-83fc-b0ce5e0e7359.png)

This the HTML that renders this component

```html
<div class="post-notice new-user"><p><svg class="fa d-icon d-icon-hands-helping svg-icon svg-node" aria-hidden="true"><use xlink:href="#hands-helping"></use></svg>This is the first time Orlando has posted — let’s welcome them to our community!</p></div>
```

**Why:** To fix the bug

**How:**

- New user notice shouldn't be bigger or overflow posts container

**Comment by duranmla** [comment]
This one has been addressed within the new theme
