### ISSUE TITLE
Award badge when user joins the Strike campaign

### ISSUE THREAD

**Issue by orlando** [debtcollective/community#21]
**What:** Award badge when user joins the Strike campaign

**Why:** To reward the users that join the strike campaign. Information about this can be shown in the "Welcome" page we have after the user joins a campaign.

**How:**

- Create the badge in Discourse
- Initially, the awarding of the badge can be done manually, but Ideally, we want to award them automatically. A way to do this is to add users that join the campaign to a specific Discourse group and assign a badge to the Discourse group. If we can show the badge as part of their username it would be better.

**Comment by duranmla** [comment]
This has been addressed at https://github.com/debtcollective/campaign-api/pull/39
