### ISSUE TITLE
Prototype new community design

### ISSUE THREAD

**Issue by orlando** [debtcollective/community#24]
**What:** Prototype new community design

**Why:** We started working on a new design for the community. We will be moving to a card-based design from the current tables Discourse has. 

The idea is remove all the power users feature Discourse has and make the UI simpler, with focus on making the navigation easier.

**How:**

- Implement design and make a prototype available for users
- Consider mobile designs and prototype

**Comment by duranmla** [comment]
Mocks has been built already at https://www.figma.com/file/iab7UEbGQhAWcsubYZ9cWB/community-mockups?node-id=0%3A1
