### ISSUE TITLE
Add initial page with categories card

### ISSUE THREAD

**Issue by duranmla** [debtcollective/community#28]
**What:** Initial page with categories
![image](https://user-images.githubusercontent.com/1425162/72452550-08d96400-37be-11ea-8e9a-9ee685be8180.png)

[Link to the component](https://sketch.cloud/s/54jwx/a/GWxJJD)

- [x] Show collectives categories
- [x] Show "others" categories
- [x] Replace mobile/desktop templates
- ~Show amount of participants~ #33
- [x] Show amount of topics

**Acceptance criteria:** The categories that are being shown here are "collectives" (categories with special field of "is_collective") and "others" which are the rest of them.

**Comment by duranmla** [comment]
Let's highlight the fact that we don't need the "show more" functionality

**Comment by duranmla** [comment]
@orlando what's the criteria to pick one border colour on the card or another? Within the screenshot we can see blue and red

**Comment by orlando** [comment]
@duranmla this is the color the category has in DIscourse

![image](https://user-images.githubusercontent.com/849872/72905708-935a2000-3cf6-11ea-8743-44b46d958e92.png)

**Comment by duranmla** [comment]
After merge the https://github.com/debtcollective/discourse-debtcollective-theme/pull/12 what we need to do is to also replace the mobile template because Discourse deliver other code for mobile devices.

**Comment by duranmla** [comment]
We miss the fact of render participants and amount of topics, I add to the todo list and I am going to address it before closing this issue

**Comment by duranmla** [comment]
Adding the metadata I realise that we don't have the "people" meta related on the current production view. In that sense, what it suppose to represent? _(the amount of people participating within that category?)_

The version is now in production only shows the total topic count _(the standard for discourse)_

![image](https://user-images.githubusercontent.com/1425162/73431779-7a2e2080-4341-11ea-9758-b66d38e96c3b.png)

If we want to add the counter of people within the category, I will create a different issue and then make it happen after the event once all the base things we have on reach has been done

**Comment by duranmla** [comment]
Further improvement for counter of member at https://github.com/debtcollective/community/issues/33

**Comment by duranmla** [comment]
With the above being merged we can close this ticket.
