### ISSUE TITLE
Letter avatars are not loading

### ISSUE THREAD

**Issue by orlando** [debtcollective/community#3]
Letter avatars are returning 404 in Discourse

![image](https://user-images.githubusercontent.com/849872/53293674-feb90c00-378c-11e9-8ee0-5cab8cc80d9e.png)

This can be either a bug in our installation or the discourse letter avatars proxy not working correctly.

## Acceptance Criteria

- Letter avatars should render correctly

**Comment by orlando** [comment]
If we disable `external system avatars enabled` in the Discourse settings, avatars render correctly. We have disabled that but I would want this option to be enabled again.

I'll leave this ticket open until we find the reason why is not working with the letter avatar proxy Discourse provides

**Comment by duranmla** [comment]
I think this has been already addressed
