### ISSUE TITLE
Add members counter to collectives

### ISSUE THREAD

**Issue by duranmla** [debtcollective/community#33]
**What:**
We need to render the amount of members in a collective

**Why:**
Related to the categories page customisation

**Comment by duranmla** [comment]
Here we "suffer" similar to #34 since we need to do a backend customisation which is outside the capacity of the theme. _(we need the plugin capabilities)_ https://meta.discourse.org/t/perform-backend-customisations-with-themes/144212

**Comment by orlando** [comment]
This was implemented
