### ISSUE TITLE
Add support to display topic description

### ISSUE THREAD

**Issue by duranmla** [debtcollective/community#34]
**What:**
Within the topic list user should be able to see an excerpt of the content

**Why:**
Refers to customisation at #29 but Discourse doesn't have that built-in

**Comment by duranmla** [comment]
There is a `has_summary` property but doesn't seems to be for what we need
![image](https://user-images.githubusercontent.com/1425162/73822432-6168b380-47f6-11ea-8d6a-c895565eda6c.png)

**Comment by duranmla** [comment]
I have been doing some research related to this, thing is that by default topics doesn't come with the "excerpt" which correspond to a portion of text from the first post. The topic component is also used to render categories which does have excerpt support.

With that being said:
1. We can make a request to load the post stream from a topic and get the description from there. Similar to what is being done at https://github.com/discourse/discourse/blob/fe588cc7f8c4d2b6100b59d9b3bed0f7efb5b893/app/assets/javascripts/discourse/models/post-stream.js.es6#L275 but sounds overkill 
2. Perform some backend customisation but themes can't do so https://meta.discourse.org/t/perform-backend-customisations-with-themes/144212 instead we should create a plugin to do something like https://github.com/discourse/discourse-tooltips/blob/master/app/controllers/discourse_tooltips/tooltip_previews_controller.rb

There is a lot of friction to do this so depends on the importance we may want to skip it. By now I will remove it from the "Theme creation milestone" as I don't consider it basic

**Comment by orlando** [comment]
This was implemented
