### ISSUE TITLE
Setup testing instance for community

### ISSUE THREAD

**Issue by orlando** [debtcollective/community#9]
Right now we don't have a test environment where we can test discourse upgrades or plugins before moving them to production. This may lead to problems with upgrades or new plugins break the code.

The goal is to set up a testing environment where we deploy.

## Acceptance Criteria

- We have a testing environment that uses the same configuration as production.

**Comment by duranmla** [comment]
Do we really need this? What happen with the preview feature? Besides, discourse have  `/safe-mode` path in order to resolve issues by removing all plugins and allow us to get back on track.
